/* ========================================================================
 * Copyright 2014 grupo1
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 grupo1

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201408112050

*/
define(['controller/_cursoController','delegate/cursoDelegate'], function() {
    App.Controller.CursoController = App.Controller._CursoController.extend({
        mostrarSecciones: function(){
            alert('Usted quiere ver las secciones hola');
        },
        postInit: function(){
            var self = this;
            this.listVerSeccionesTemplate = _.template($('#verSeccionesList').html());
            this.listverSeccionesModelClass = options.listModelClass;
        },
        _renderSecciones: function(){
            var self = this;
            /*Aquí se utiliza el efecto gráfico backbone deslizar. “$el” hace referencia al <div id=”main”> ubicado en el index.html. Dentro de este div se despliegue la tabla.*/
            this.$el.slideUp("fast", function() {
                /*Establece que en el <div> se despliegue el template de la variable “”. Como parámetros entran las variables establecidas dentro de los tags <%%> con sus valores como un objeto JSON. En este caso, la propiedad sports tendrá la lista que instanció “sportSearch” en la variable del bucle <% _.each(sports, function(sport) { %>*/
 
                self.$el.html(self.listPromedioTemplate({cursos: self.verSeccionesModelList.models}));
                self.$el.slideDown("fast");
            });
        }
    });
    return App.Controller.CursoController;
}); 